# Generated by Django 4.2.16 on 2026-04-19 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('carpet_area', models.PositiveIntegerField(help_text='Area in sq.ft')),
                ('bedrooms', models.PositiveIntegerField()),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('parking_available', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(default='api', max_length=32)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('caller_utterance', models.TextField()),
                ('agent_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='properties.property')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
